### ISSUE TITLE
Geckolib Fabric/SoulsWeapons/Ars Nouveau crash

### ISSUE THREAD

**Issue by Zainyest** [Sinytra/ConnectorExtras#11] opened 2023-10-25 23:27 UTC
### Describe the bug

Using Geckolib fabric or forge with Marium Soulslike Weaponry and Ars Nouveau Crashes during initialization.

### Steps to reproduce

1. Compile & install newest branch of ConnectorExtras with the newest releases for connector; install the following mods:
![image](https://github.com/Sinytra/ConnectorExtras/assets/32520656/2644c9d9-8ead-47d3-97b0-f5ca98ae012e)

2. Launch MC.
3. Experience crash during initialization.

### Logs

https://pastebin.com/nh33zQV4

### Additional context

 Compiled the dev master branch for ConnectorExtras to get past a pehkui mixin error but got a different geckolib error during startup. Looking at other issues here, it seems other mods that can use geckolib fabric are present like Bosses of Mass Destruction but some cannot.

**Comment by Zainyest** [comment] 2023-10-25 23:29
Woah those logs don't look right, lemme try uploading again lol

**Comment by Zainyest** [comment] 2023-10-25 23:32
used pastebin and it worked

**Comment by Zainyest** [comment] 2023-10-25 23:47
Tested without Ars Nouveau and works fine, probably something to do with Souls wanting a fabric version and ConnectorExtras adding a forge bridge. Without Soulslike Weaponry the fabric version of GeckoLib works fine with Ars Nouveau as well.

**Comment by Xeno123456789** [comment] 2023-10-26 00:02
The issue is that Marium’s Soulslike uses Fabric Geckolib, and Ars uses Forge Geckolib. You can’t use these mods together because Geckolib is weird. You have to choose one.

**Comment by Zainyest** [comment] 2023-10-26 00:18
> The issue is that Marium’s Soulslike uses Fabric Geckolib, and Ars uses Forge Geckolib. You can’t use these mods together because Geckolib is weird. You have to choose one.

Yeah, some of the time; but some mods do work with fabric and Ars, like Bosses of Mass Destruction which is why I added this as an issue. (just tested BOMD with the modlist here and it works without soulslike)

**Comment by coco875** [comment] 2023-10-26 04:45
Related to https://github.com/Sinytra/Connector/issues/231

**Comment by coco875** [comment] 2023-10-26 04:47
> The issue is that Marium’s Soulslike uses Fabric Geckolib, and Ars uses Forge Geckolib. You can’t use these mods together because Geckolib is weird. You have to choose one.

It's more complicated it's because ars nouveau have geckolib in the mod and so like forge mod are load before fabric he use this version of geckolib instead of the fabric version

**Comment by Su5eD** [comment] 2023-10-26 11:20
The error happens because Geckolib for Fabric and Forge have different code - they're not using a multiloader layout like other libraries.

I'll close this in favor of #231 where geckolib compat is being tracked.

**Closed** 2023-10-26 11:21 UTC
Labels: bug
